recaptcha {
	// Set to false to disable the display of captcha
	enabled = true
	
	// These keys are generated by the ReCaptcha service
	publicKey = ""
	privateKey = ""
   
	// Include the noscript tags in the generated captcha
	includeNoScript = true
	
	// Communicate using HTTPS
	useSecureAPI = false
}